#!/bin/bash

export CUDA_VISIBLE_DEVICES=-1

train_images_file="./SYMBOLS_DATA/DATA_TRAIN_IMAGES.npy"
train_labels_file="./SYMBOLS_DATA/DATA_TRAIN_LABELS.npy"
convnet_file="./CONVNET_DATA/convnet.pkl"
learning_rate=0.001
batch_size=64
n_input=1024
n_hidden=512
n_first_digit_length=1
n_second_digit_length=1
training_iters=30000
display_step=10
model_filename="./model.ckpt"
test_images_file="./SYMBOLS_DATA/DATA_TEST_IMAGES.npy"
test_labels_file="./SYMBOLS_DATA/DATA_TEST_LABELS.npy"
test_seed=2016
test_batch_size=1000

args="$train_images_file $train_labels_file $convnet_file $learning_rate $batch_size $n_input $n_hidden $n_first_digit_length $n_second_digit_length $training_iters $display_step $model_filename $test_images_file $test_labels_file $test_seed $test_batch_size"

echo $args

cd sequential-operations
python -u run.py $args
